version: '3.8'
services:
  # Frontend
  frontend:
    build:
      context: ../frontend
    container_name: frontend
    volumes:
    - react_build:/frontend/build

  # Nginx service
  nginx:
    image: nginx:1.21
    ports:
    - 80:80
    volumes:
    - ./local_nginx:/etc/nginx/conf.d
    - react_build:/usr/share/nginx/html
    command: "/bin/sh nginx -g \"daemon off;\""
    depends_on:
      - frontend
    restart: always

# Volumes
volumes:
  node1-vol:
  node2-vol:
  node3-vol:
  react_build: